---

- name: Install nginx
  apt: pkg=nginx state=installed update_cache=true
  sudo: yes
  notify:
    - start nginx

- name: Copy index.html
  copy: src=index.html dest=/usr/share/nginx/www mode=0644
  sudo: yes
  notify:
    - start nginx

- name: Copy configuration file
  template: src=blog.j2 dest=/etc/nginx/conf.d/blog.conf mode=0644
  sudo: yes
  notify:
    - start nginx
