---

# Description: Installs nodejs from source
#
- name: Node.js | Check if node is installed
  stat: path={{node_path}} follow=True
  register: node_available

- name: Node.js | Fetching node.js source
  action: get_url url=http://nodejs.org/dist/v{{node_version}}/{{node_tarball}} dest=/tmp/
  when: node_available.stat.exists == False

- name: Node.js | Unpack node.js tarball
  command: tar zxf {{node_tarball}} chdir=/tmp
  when: node_available.stat.exists == False

- name: Node.js | Configure
  shell: /usr/bin/python ./configure --prefix={{prefix}} chdir=/tmp/{{node_prefix}}
  when: node_available.stat.exists == False

- name: Node.js | Make
  shell: /usr/bin/make chdir=/tmp/{{node_prefix}}
  when: node_available.stat.exists == False

- name: Node.js | Make install
  shell: /usr/bin/make install chdir=/tmp/{{node_prefix}}
  sudo: yes
  when: node_available.stat.exists == False
