---
# Description: Installs nodejs from source
#
- name: Node.js | Check if node is installed
  local_action: stat path=/usr/local/bin/node
  register: wanted_version_installed

- name: Node.js | Fetching node.js source
  action: get_url url=http://nodejs.org/dist/v{{node_version}}/{{node_tarball}} dest=/tmp/
  when: wanted_version_installed.rc == 1

- name: Node.js | Unpack node.js tarball
  command: tar zxf {{node_tarball}} chdir=/tmp
  when: wanted_version_installed.rc == 1

- name: Node.js | Configure
  shell: /usr/bin/python ./configure --prefix={{node_path}} chdir=/tmp/{{node_prefix}}
  when: wanted_version_installed.rc == 1

- name: Node.js | Make
  shell: /usr/bin/make chdir=/tmp/{{node_prefix}}
  when: wanted_version_installed.rc == 1

- name: Node.js | Make install
  shell: /usr/bin/make install chdir=/tmp/{{node_prefix}}
  sudo: yes
  when: wanted_version_installed.rc == 1
