---

- name: update system
  apt:  update_cache=yes cache_valid_time=86400
  sudo: yes

- name: upgrade system
  apt: upgrade=dist
  sudo: yes

- name: install system packages
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - git
    - python-dev
    - python-pip
    - python-setuptools
    - python-virtualenv
    - curl
    - wget
  sudo: yes

- name: set timezone to UTC
  file: src=/usr/share/zoneinfo/UTC path=/etc/localtime state=link force=yes
  sudo: yes
  notify: restart cron
