---

- name: Checkout blog-client
  git: repo=https://github.com/dbajpeyi/blog-client.git dest=blog-client

- name: Install grunt
  shell: /usr/local/bin/npm install -g grunt-cli
  sudo: true

- name: Install dependencies
  shell: /usr/local/bin/npm install chdir={{ root }}/blog-client

- name: Grunt build
  shell: /usr/local/bin/grunt build chdir={{ root }}/blog-client
