---

- name: install uwsgi
  pip: name=uwsgi state=present
  sudo: yes

- name: create uwsgi directory
  file: path=/etc/uwsgi state=directory mode=0755
  sudo: yes

- name: configure uwsgi
  template: src=uwsgi.ini.j2 dest=/etc/uwsgi/todo.ini
  sudo: yes

- name: Checkout todo-server
  git: repo=https://github.com/caulagi/todo-server.git dest=todo-server

- name: Setup todo-server
  # Use full path: https://github.com/ansible/ansible/issues/6437
  pip: >
    requirements=/home/{{ user }}/todo-server/requirements.txt
    virtualenv=/home/{{ user }}/venv/todo
    state=present

- name: Run tests for todo-server
  shell: "/bin/bash /home/{{ user }}/venv/todo/bin/activate && cd /home/{{ user }}/todo-server && /home/{{ user }}/venv/todo/bin/py.test"

- name: Start server with uwsgi
  command: /usr/local/bin/uwsgi --ini /etc/uwsgi/todo.ini
  sudo: yes
  notify:
    - restart nginx
